"""Supervisor agent module for managing research delegation.

This module contains the supervisor agent that plans research strategy,
delegates to researchers, and coordinates the overall research process.
"""

import asyncio
from typing import Literal, cast

from langchain_core.messages import AIMessage, HumanMessage, ToolMessage
from langgraph.graph import END, START, StateGraph
from langgraph.types import Command

from fathom.config.loader import ConfigLoader
from fathom.config.logging import get_logger
from fathom.models.schema import (
    ConductResearch,
    ResearchComplete,
    SupervisorState,
)
from fathom.tools.search import build_model
from fathom.tools.utils import get_notes_from_tool_calls, think_tool

settings = ConfigLoader()
logger = get_logger(__name__)


async def supervisor(state: SupervisorState):
    """
    Lead research supervisor that plans research strategy and delegates to researchers.

    The supervisor analyzes the research brief and decides how to break down the research
    into manageable tasks. It can use think_tool for strategic planning, ConductResearch
    to delegate tasks to sub-researchers, or ResearchComplete when satisfied with findings.

    Args:
        state: Current supervisor state with messages and research context

    Returns:
        Command to proceed to supervisor_tools for tool execution
    """
    current_iteration = state.get("research_iterations", 0)
    logger.info("=" * 60)
    logger.info(f"SUPERVISOR ITERATION #{current_iteration + 1}: Starting")
    logger.info("=" * 60)

    lead_researcher_tools = [ConductResearch, ResearchComplete, think_tool]

    research_model = build_model(settings.research_model).bind_tools(
        lead_researcher_tools
    )
    logger.debug(f"Using model: {settings.research_model}")
    logger.debug(
        f"Available tools: {[t.__name__ if hasattr(t, '__name__') else str(t) for t in lead_researcher_tools]}"
    )

    supervisor_messages = state.get("supervisor_messages", [])
    logger.info(f"Processing {len(supervisor_messages)} supervisor messages")
    logger.debug(f"Message types: {[type(m).__name__ for m in supervisor_messages]}")

    logger.debug("Invoking supervisor model...")

    # Use streaming to avoid timeouts with reasoning models
    # Accumulate chunks using LangChain's pattern
    from langchain_core.messages import AIMessageChunk

    response = None
    async for chunk in research_model.astream(supervisor_messages):
        if response is None:
            response = chunk
        else:
            # Use AIMessageChunk's __add__ to properly merge chunks
            if isinstance(chunk, AIMessageChunk):
                response = response + chunk
            else:
                response = chunk

    # Fallback if no response received
    if response is None:
        response = AIMessage(content="")

    # Log tool calls if any
    if hasattr(response, "tool_calls") and response.tool_calls:
        tool_names = [tc.get("name", "unknown") for tc in response.tool_calls]
        logger.info(
            f"✓ Supervisor decided to call {len(response.tool_calls)} tool(s): {', '.join(tool_names)}"
        )
        for i, tc in enumerate(response.tool_calls, 1):
            logger.debug(
                f"  Tool #{i}: {tc.get('name')} with args: {str(tc.get('args', {}))[:100]}"
            )
    else:
        logger.warning("⚠ No tool calls generated by supervisor")

    # Updatte state and proceed to tool execution
    logger.info(
        f"→ Routing to: supervisor_tools (iteration will be {current_iteration + 1})"
    )

    return Command(
        goto="supervisor_tools",
        update={
            "supervisor_messages": [response],
            "research_iterations": state.get("research_iterations", 0) + 1,
        },
    )


async def supervisor_tools(
    state: SupervisorState,
) -> Command[Literal["supervisor", "__end__"]]:
    """
    Execute tools called by the supervisor, including research delegation and strategic thinking.

    This function handles three types of supervisor tool calls:
    1. think_tool - Strategic reflection that continues the conversation
    2. ConductResearch - Delegates research tasks to sub-researchers
    3. ResearchComplete - Signals completion of research phase

    Args:
        state: Current supervisor state with messages and iteration count

    Returns:
        Command to either continue supervision loop or end research phase
    """
    # Extract current state and check exit conditions
    supervisor_messages = state.get("supervisor_messages", [])
    research_iterations = state.get("research_iterations", 0)
    most_recent_message = cast(AIMessage, supervisor_messages[-1])

    logger.info(f"Supervisor tools executing at iteration {research_iterations}")

    # Define exit criteria for research phase
    exceed_allowed_iterations = (
        research_iterations > settings.config["research"]["max_depth"]
    )
    no_tool_calls = not most_recent_message.tool_calls
    research_complete_tool_call = any(
        tool_call["name"] == "ResearchComplete"
        for tool_call in most_recent_message.tool_calls
    )

    # Check exit conditions and log appropriately
    if exceed_allowed_iterations:
        logger.warning(
            f"Research exceeded max depth ({settings.config['research']['max_depth']} iterations), "
            "ending research phase"
        )
    elif no_tool_calls:
        logger.warning(
            "No tool calls found in supervisor message, ending research phase"
        )
    elif research_complete_tool_call:
        logger.info("ResearchComplete tool called, ending research phase")

    if exceed_allowed_iterations or no_tool_calls or research_complete_tool_call:
        logger.info("Finalizing research and extracting notes")
        return Command(
            goto=cast(Literal["__end__"], END),
            update={
                "notes": get_notes_from_tool_calls(supervisor_messages),
                "research_brief": state.get("research_brief", ""),
            },
        )

    # Process all tool calls together (both think_tool and ConductResearch)
    all_tool_messages = []
    update_payload = {"supervisor_messages": []}

    # Handle think_tool calls (strategic reflection)
    think_tool_calls = [
        tool_call
        for tool_call in most_recent_message.tool_calls
        if tool_call["name"] == "think_tool"
    ]

    for tool_call in think_tool_calls:
        reflection_content = tool_call["args"]["reflection"]
        all_tool_messages.append(
            ToolMessage(
                content=f"Reflection recorded: {reflection_content}",
                name="think_tool",
                tool_call_id=tool_call["id"],
            )
        )

    # Handle ConductResearch calls (research delegation)
    conduct_research_calls = [
        tool_call
        for tool_call in most_recent_message.tool_calls
        if tool_call["name"] == "ConductResearch"
    ]

    if conduct_research_calls:
        try:
            # Import researcher_subgraph here to avoid circular dependency
            from fathom.agents.researcher import researcher_subgraph

            # Limit concurrent research units to prevent resource exhaustion
            allowed_conduct_research_calls = conduct_research_calls[
                : settings.config["research"]["concurrency"]
            ]
            overflow_conduct_research_calls = conduct_research_calls[
                settings.config["research"]["concurrency"] :
            ]

            # Execute research tasks in parallel
            research_tasks = [
                researcher_subgraph.ainvoke(
                    {
                        "researcher_messages": [
                            HumanMessage(content=tool_call["args"]["research_topic"])
                        ],
                        "research_topic": tool_call["args"]["research_topic"],
                    },
                )
                for tool_call in allowed_conduct_research_calls
            ]

            tool_results = await asyncio.gather(*research_tasks)

            # Create tool messages with research results
            for observation, tool_call in zip(
                tool_results, allowed_conduct_research_calls
            ):
                all_tool_messages.append(
                    ToolMessage(
                        content=observation.get(
                            "compressed_research",
                            "Error synthesizing research report: Maximum retries exceeded",
                        ),
                        name=tool_call["name"],
                        tool_call_id=tool_call["id"],
                    )
                )

            # Handle overflow research calls with error messages
            for overflow_call in overflow_conduct_research_calls:
                all_tool_messages.append(
                    ToolMessage(
                        content=f"Error: Did not run this research as you have already exceeded the maximum number of concurrent research units. Please try again with {settings.config['research']['concurrency']} or fewer research units.",
                        name="ConductResearch",
                        tool_call_id=overflow_call["id"],
                    )
                )

            # Aggregate raw notes from all research results
            raw_notes_concat = "\n".join(
                [
                    "\n".join(observation.get("raw_notes", []))
                    for observation in tool_results
                ]
            )

            if raw_notes_concat:
                update_payload["raw_notes"] = [raw_notes_concat]
        except Exception:
            # Handle research execution errors
            return Command(
                goto=cast(Literal["__end__"], END),
                update={
                    "notes": get_notes_from_tool_calls(supervisor_messages),
                    "research_brief": state.get("research_brief", ""),
                },
            )

    # Return command with all tool results
    update_payload["supervisor_messages"] = all_tool_messages
    return Command(goto="supervisor", update=update_payload)


# Supervisor Subgraph Construction
# Create the supervisor workflow that manages research delegation and coordination
supervisor_builder = StateGraph(SupervisorState)

# Add supervisor nodes for research management
supervisor_builder.add_node("supervisor", supervisor)
supervisor_builder.add_node("supervisor_tools", supervisor_tools)

# Define supervisor workflow edges
supervisor_builder.add_edge(START, "supervisor")

# Compile supervisor subgraph for use in main workflow
supervisor_subgraph = supervisor_builder.compile()
